services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: kg-postgres
    environment:
      POSTGRES_USER: kb_user
      POSTGRES_PASSWORD: kb_password
      POSTGRES_DB: knowledge_base
    # Проброс порта убран (конфликт с локальным PostgreSQL)
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: kg-redis
    ports:
      - "6379:6379"

  # nlp:
  #   build: ./nlp-service
  #   container_name: kg-nlp
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - MODEL_NAME=all-MiniLM-L6-v2
  #   volumes:
  #     - ./huggingface_cache:/root/.cache/huggingface
  #   restart: always

  backend:
    build: ./backend
    container_name: kg-backend
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://kb_user:kb_password@postgres:5432/knowledge_base?sslmode=disable
      REDIS_URL: redis://redis:6379
      NLP_SERVICE_URL: http://host.docker.internal:5000
    depends_on:
      - postgres
      - redis
      # - nlp
    # volumes:
    #   - ./backend:/app

  worker:
    build: ./backend
    container_name: kg-worker
    command: ["./worker"]
    environment:
      DATABASE_URL: postgresql://kb_user:kb_password@postgres:5432/knowledge_base?sslmode=disable
      REDIS_URL: redis://redis:6379
      NLP_SERVICE_URL: http://host.docker.internal:5000
    depends_on:
      - postgres
      - redis
      # - nlp
    # volumes:
    #   - ./backend:/app

volumes:
  postgres_data: