#!/usr/bin/env python3
"""Remove temporary test artifacts generated by backend/frontend/NLP tests."""

import argparse
import glob
import os
import shutil
import sys
from pathlib import Path


def project_root() -> Path:
    return Path(__file__).resolve().parents[2]


def remove_path(path: Path, dry_run: bool) -> bool:
    if not path.exists():
        return False
    rel = path.relative_to(project_root())
    if dry_run:
        print(f"[DRY-RUN] would remove: {rel}")
        return True
    try:
        if path.is_dir():
            shutil.rmtree(path)
        else:
            path.unlink()
        print(f"Removed: {rel}")
        return True
    except OSError as exc:
        print(f"Failed to remove {rel}: {exc}", file=sys.stderr)
        return False


def main() -> int:
    parser = argparse.ArgumentParser(description="Clean temporary test artifacts")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be removed without deleting",
    )
    args = parser.parse_args()

    root = project_root()
    patterns = [
        "backend/coverage.out",
        "backend/.coverage_tmp",
        "backend/*.cov",
        "frontend/coverage",
        "logs/test-outputs/*.log",
        "scripts/testing/temp/snapshots/*",
    ]

    removed = 0
    for pattern in patterns:
        for match in glob.glob(str(root / pattern), recursive=False):
            path = Path(match)
            if remove_path(path, args.dry_run):
                removed += 1

    action = "would remove" if args.dry_run else "removed"
    print(f"Temporary test artifacts {action}: {removed} items")
    return 0


if __name__ == "__main__":
    sys.exit(main())
