// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.13.0
// source: graph_layout.proto

package graphservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphService_GetNoteLayout_FullMethodName      = "/graphservice.GraphService/GetNoteLayout"
	GraphService_GetFullLayout_FullMethodName      = "/graphservice.GraphService/GetFullLayout"
	GraphService_GetDelta_FullMethodName           = "/graphservice.GraphService/GetDelta"
	GraphService_GetNeighbors_FullMethodName       = "/graphservice.GraphService/GetNeighbors"
	GraphService_GetPath_FullMethodName            = "/graphservice.GraphService/GetPath"
	GraphService_GetRecommendations_FullMethodName = "/graphservice.GraphService/GetRecommendations"
)

// GraphServiceClient is the client API for GraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraphServiceClient interface {
	GetNoteLayout(ctx context.Context, in *NoteLayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error)
	GetFullLayout(ctx context.Context, in *FullLayoutRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LayoutChunk], error)
	GetDelta(ctx context.Context, in *DeltaRequest, opts ...grpc.CallOption) (*DeltaResponse, error)
	GetNeighbors(ctx context.Context, in *NeighborRequest, opts ...grpc.CallOption) (*NeighborResponse, error)
	GetPath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*PathResponse, error)
	GetRecommendations(ctx context.Context, in *RecommendationsRequest, opts ...grpc.CallOption) (*RecommendationsResponse, error)
}

type graphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphServiceClient(cc grpc.ClientConnInterface) GraphServiceClient {
	return &graphServiceClient{cc}
}

func (c *graphServiceClient) GetNoteLayout(ctx context.Context, in *NoteLayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LayoutResponse)
	err := c.cc.Invoke(ctx, GraphService_GetNoteLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GetFullLayout(ctx context.Context, in *FullLayoutRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LayoutChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GraphService_ServiceDesc.Streams[0], GraphService_GetFullLayout_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FullLayoutRequest, LayoutChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_GetFullLayoutClient = grpc.ServerStreamingClient[LayoutChunk]

func (c *graphServiceClient) GetDelta(ctx context.Context, in *DeltaRequest, opts ...grpc.CallOption) (*DeltaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeltaResponse)
	err := c.cc.Invoke(ctx, GraphService_GetDelta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GetNeighbors(ctx context.Context, in *NeighborRequest, opts ...grpc.CallOption) (*NeighborResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NeighborResponse)
	err := c.cc.Invoke(ctx, GraphService_GetNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GetPath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*PathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PathResponse)
	err := c.cc.Invoke(ctx, GraphService_GetPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GetRecommendations(ctx context.Context, in *RecommendationsRequest, opts ...grpc.CallOption) (*RecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendationsResponse)
	err := c.cc.Invoke(ctx, GraphService_GetRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphServiceServer is the server API for GraphService service.
// All implementations must embed UnimplementedGraphServiceServer
// for forward compatibility.
type GraphServiceServer interface {
	GetNoteLayout(context.Context, *NoteLayoutRequest) (*LayoutResponse, error)
	GetFullLayout(*FullLayoutRequest, grpc.ServerStreamingServer[LayoutChunk]) error
	GetDelta(context.Context, *DeltaRequest) (*DeltaResponse, error)
	GetNeighbors(context.Context, *NeighborRequest) (*NeighborResponse, error)
	GetPath(context.Context, *PathRequest) (*PathResponse, error)
	GetRecommendations(context.Context, *RecommendationsRequest) (*RecommendationsResponse, error)
	mustEmbedUnimplementedGraphServiceServer()
}

// UnimplementedGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphServiceServer struct{}

func (UnimplementedGraphServiceServer) GetNoteLayout(context.Context, *NoteLayoutRequest) (*LayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNoteLayout not implemented")
}
func (UnimplementedGraphServiceServer) GetFullLayout(*FullLayoutRequest, grpc.ServerStreamingServer[LayoutChunk]) error {
	return status.Errorf(codes.Unimplemented, "method GetFullLayout not implemented")
}
func (UnimplementedGraphServiceServer) GetDelta(context.Context, *DeltaRequest) (*DeltaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelta not implemented")
}
func (UnimplementedGraphServiceServer) GetNeighbors(context.Context, *NeighborRequest) (*NeighborResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNeighbors not implemented")
}
func (UnimplementedGraphServiceServer) GetPath(context.Context, *PathRequest) (*PathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPath not implemented")
}
func (UnimplementedGraphServiceServer) GetRecommendations(context.Context, *RecommendationsRequest) (*RecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecommendations not implemented")
}
func (UnimplementedGraphServiceServer) mustEmbedUnimplementedGraphServiceServer() {}
func (UnimplementedGraphServiceServer) testEmbeddedByValue()                      {}

// UnsafeGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphServiceServer will
// result in compilation errors.
type UnsafeGraphServiceServer interface {
	mustEmbedUnimplementedGraphServiceServer()
}

func RegisterGraphServiceServer(s grpc.ServiceRegistrar, srv GraphServiceServer) {
	// If the following call pancis, it indicates UnimplementedGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphService_ServiceDesc, srv)
}

func _GraphService_GetNoteLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetNoteLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetNoteLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetNoteLayout(ctx, req.(*NoteLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GetFullLayout_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FullLayoutRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraphServiceServer).GetFullLayout(m, &grpc.GenericServerStream[FullLayoutRequest, LayoutChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GraphService_GetFullLayoutServer = grpc.ServerStreamingServer[LayoutChunk]

func _GraphService_GetDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetDelta(ctx, req.(*DeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GetNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeighborRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetNeighbors(ctx, req.(*NeighborRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GetPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetPath(ctx, req.(*PathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GetRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetRecommendations(ctx, req.(*RecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphService_ServiceDesc is the grpc.ServiceDesc for GraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphservice.GraphService",
	HandlerType: (*GraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNoteLayout",
			Handler:    _GraphService_GetNoteLayout_Handler,
		},
		{
			MethodName: "GetDelta",
			Handler:    _GraphService_GetDelta_Handler,
		},
		{
			MethodName: "GetNeighbors",
			Handler:    _GraphService_GetNeighbors_Handler,
		},
		{
			MethodName: "GetPath",
			Handler:    _GraphService_GetPath_Handler,
		},
		{
			MethodName: "GetRecommendations",
			Handler:    _GraphService_GetRecommendations_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFullLayout",
			Handler:       _GraphService_GetFullLayout_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "graph_layout.proto",
}
