// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.0.0
// source: graph_layout.proto

package graphservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GraphService_GetNoteLayout_FullMethodName = "/graphservice.GraphService/GetNoteLayout"
	GraphService_GetFullLayout_FullMethodName = "/graphservice.GraphService/GetFullLayout"
	GraphService_GetDelta_FullMethodName      = "/graphservice.GraphService/GetDelta"
)

// GraphServiceClient is the client API for GraphService service.
//
// For semantics around ctx use and closing a streaming call, please refer to https://pkg.go.dev/google.golang.org/grpc#ClientConn.NewStream.
type GraphServiceClient interface {
	// GetNoteLayout returns the layout for a specific note and its neighbors
	GetNoteLayout(ctx context.Context, in *NoteLayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error)
	// GetFullLayout streams the full graph layout in chunks
	GetFullLayout(ctx context.Context, in *FullLayoutRequest, opts ...grpc.CallOption) (GraphService_GetFullLayoutClient, error)
	// GetDelta returns the delta between two layout versions
	GetDelta(ctx context.Context, in *DeltaRequest, opts ...grpc.CallOption) (*DeltaResponse, error)
}

type graphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphServiceClient(cc grpc.ClientConnInterface) GraphServiceClient {
	return &graphServiceClient{cc}
}

func (c *graphServiceClient) GetNoteLayout(ctx context.Context, in *NoteLayoutRequest, opts ...grpc.CallOption) (*LayoutResponse, error) {
	out := new(LayoutResponse)
	err := c.cc.Invoke(ctx, GraphService_GetNoteLayout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphServiceClient) GetFullLayout(ctx context.Context, in *FullLayoutRequest, opts ...grpc.CallOption) (GraphService_GetFullLayoutClient, error) {
	stream, err := c.cc.NewStream(ctx, &GraphService_ServiceDesc.Streams[0], GraphService_GetFullLayout_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &graphServiceGetFullLayoutClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GraphService_GetFullLayoutClient interface {
	Recv() (*LayoutChunk, error)
	grpc.ClientStream
}

type graphServiceGetFullLayoutClient struct {
	grpc.ClientStream
}

func (x *graphServiceGetFullLayoutClient) Recv() (*LayoutChunk, error) {
	m := new(LayoutChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *graphServiceClient) GetDelta(ctx context.Context, in *DeltaRequest, opts ...grpc.CallOption) (*DeltaResponse, error) {
	out := new(DeltaResponse)
	err := c.cc.Invoke(ctx, GraphService_GetDelta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphServiceServer is the server API for GraphService service.
// All implementations must embed UnimplementedGraphServiceServer
// for forward compatibility
type GraphServiceServer interface {
	// GetNoteLayout returns the layout for a specific note and its neighbors
	GetNoteLayout(context.Context, *NoteLayoutRequest) (*LayoutResponse, error)
	// GetFullLayout streams the full graph layout in chunks
	GetFullLayout(*FullLayoutRequest, GraphService_GetFullLayoutServer) error
	// GetDelta returns the delta between two layout versions
	GetDelta(context.Context, *DeltaRequest) (*DeltaResponse, error)
	mustEmbedUnimplementedGraphServiceServer()
}

// UnimplementedGraphServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGraphServiceServer struct {
}

func (UnimplementedGraphServiceServer) GetNoteLayout(context.Context, *NoteLayoutRequest) (*LayoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNoteLayout not implemented")
}
func (UnimplementedGraphServiceServer) GetFullLayout(*FullLayoutRequest, GraphService_GetFullLayoutServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFullLayout not implemented")
}
func (UnimplementedGraphServiceServer) GetDelta(context.Context, *DeltaRequest) (*DeltaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDelta not implemented")
}
func (UnimplementedGraphServiceServer) mustEmbedUnimplementedGraphServiceServer() {}

// UnsafeGraphServiceServer may be embedded to opt-out of forward compatibility.
// Use this only with a full understanding of the implications of using UnsafeGraphServiceServer.
type UnsafeGraphServiceServer interface {
	mustEmbedUnimplementedGraphServiceServer()
}

func RegisterGraphServiceServer(s grpc.ServiceRegistrar, srv GraphServiceServer) {
	s.RegisterService(&GraphService_ServiceDesc, srv)
}

func _GraphService_GetNoteLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetNoteLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetNoteLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetNoteLayout(ctx, req.(*NoteLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphService_GetFullLayout_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FullLayoutRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GraphServiceServer).GetFullLayout(m, &graphServiceGetFullLayoutServer{stream})
}

type GraphService_GetFullLayoutServer interface {
	Send(*LayoutChunk) error
	grpc.ServerStream
}

type graphServiceGetFullLayoutServer struct {
	grpc.ServerStream
}

func (x *graphServiceGetFullLayoutServer) Send(m *LayoutChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _GraphService_GetDelta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeltaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphServiceServer).GetDelta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphService_GetDelta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphServiceServer).GetDelta(ctx, req.(*DeltaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphService_ServiceDesc is the gRPC service descriptor for GraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified.
var GraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "graphservice.GraphService",
	HandlerType: (*GraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNoteLayout",
			Handler:    _GraphService_GetNoteLayout_Handler,
		},
		{
			MethodName: "GetDelta",
			Handler:    _GraphService_GetDelta_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetFullLayout",
			Handler:       _GraphService_GetFullLayout_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "graph_layout.proto",
}
