// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.13.0
// source: graph_layout.proto

package graphservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoteLayoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId string `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Depth  int32  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *NoteLayoutRequest) Reset() {
	*x = NoteLayoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoteLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteLayoutRequest) ProtoMessage() {}

func (x *NoteLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteLayoutRequest.ProtoReflect.Descriptor instead.
func (*NoteLayoutRequest) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{0}
}

func (x *NoteLayoutRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NoteLayoutRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *NoteLayoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LayoutNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type  string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	X     float64 `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Z     float64 `protobuf:"fixed64,6,opt,name=z,proto3" json:"z,omitempty"`
	Size  float64 `protobuf:"fixed64,7,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *LayoutNode) Reset() {
	*x = LayoutNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutNode) ProtoMessage() {}

func (x *LayoutNode) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutNode.ProtoReflect.Descriptor instead.
func (*LayoutNode) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{1}
}

func (x *LayoutNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LayoutNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *LayoutNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LayoutNode) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *LayoutNode) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *LayoutNode) GetZ() float64 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *LayoutNode) GetSize() float64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type LayoutLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source     string  `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target     string  `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Weight     float64 `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	LinkType   string  `protobuf:"bytes,4,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	SourceType string  `protobuf:"bytes,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
}

func (x *LayoutLink) Reset() {
	*x = LayoutLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutLink) ProtoMessage() {}

func (x *LayoutLink) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutLink.ProtoReflect.Descriptor instead.
func (*LayoutLink) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{2}
}

func (x *LayoutLink) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LayoutLink) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LayoutLink) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *LayoutLink) GetLinkType() string {
	if x != nil {
		return x.LinkType
	}
	return ""
}

func (x *LayoutLink) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

type LayoutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*LayoutNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links []*LayoutLink `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	Hash  string        `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *LayoutResponse) Reset() {
	*x = LayoutResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutResponse) ProtoMessage() {}

func (x *LayoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutResponse.ProtoReflect.Descriptor instead.
func (*LayoutResponse) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{3}
}

func (x *LayoutResponse) GetNodes() []*LayoutNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *LayoutResponse) GetLinks() []*LayoutLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *LayoutResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type FullLayoutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *FullLayoutRequest) Reset() {
	*x = FullLayoutRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FullLayoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullLayoutRequest) ProtoMessage() {}

func (x *FullLayoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullLayoutRequest.ProtoReflect.Descriptor instead.
func (*FullLayoutRequest) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{4}
}

func (x *FullLayoutRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FullLayoutRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LayoutChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes   []*LayoutNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Links   []*LayoutLink `protobuf:"bytes,2,rep,name=links,proto3" json:"links,omitempty"`
	ChunkId string        `protobuf:"bytes,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
}

func (x *LayoutChunk) Reset() {
	*x = LayoutChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayoutChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayoutChunk) ProtoMessage() {}

func (x *LayoutChunk) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayoutChunk.ProtoReflect.Descriptor instead.
func (*LayoutChunk) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{5}
}

func (x *LayoutChunk) GetNodes() []*LayoutNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *LayoutChunk) GetLinks() []*LayoutLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *LayoutChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

type DeltaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LastHash string `protobuf:"bytes,2,opt,name=last_hash,json=lastHash,proto3" json:"last_hash,omitempty"`
}

func (x *DeltaRequest) Reset() {
	*x = DeltaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeltaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaRequest) ProtoMessage() {}

func (x *DeltaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaRequest.ProtoReflect.Descriptor instead.
func (*DeltaRequest) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{6}
}

func (x *DeltaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeltaRequest) GetLastHash() string {
	if x != nil {
		return x.LastHash
	}
	return ""
}

type DeltaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddedNodes   []*LayoutNode `protobuf:"bytes,1,rep,name=added_nodes,json=addedNodes,proto3" json:"added_nodes,omitempty"`
	RemovedNodes []string      `protobuf:"bytes,2,rep,name=removed_nodes,json=removedNodes,proto3" json:"removed_nodes,omitempty"`
	UpdatedNodes []*LayoutNode `protobuf:"bytes,3,rep,name=updated_nodes,json=updatedNodes,proto3" json:"updated_nodes,omitempty"`
	AddedLinks   []*LayoutLink `protobuf:"bytes,4,rep,name=added_links,json=addedLinks,proto3" json:"added_links,omitempty"`
	RemovedLinks []*LayoutLink `protobuf:"bytes,5,rep,name=removed_links,json=removedLinks,proto3" json:"removed_links,omitempty"`
	CurrentHash  string        `protobuf:"bytes,6,opt,name=current_hash,json=currentHash,proto3" json:"current_hash,omitempty"`
}

func (x *DeltaResponse) Reset() {
	*x = DeltaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeltaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaResponse) ProtoMessage() {}

func (x *DeltaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaResponse.ProtoReflect.Descriptor instead.
func (*DeltaResponse) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{7}
}

func (x *DeltaResponse) GetAddedNodes() []*LayoutNode {
	if x != nil {
		return x.AddedNodes
	}
	return nil
}

func (x *DeltaResponse) GetRemovedNodes() []string {
	if x != nil {
		return x.RemovedNodes
	}
	return nil
}

func (x *DeltaResponse) GetUpdatedNodes() []*LayoutNode {
	if x != nil {
		return x.UpdatedNodes
	}
	return nil
}

func (x *DeltaResponse) GetAddedLinks() []*LayoutLink {
	if x != nil {
		return x.AddedLinks
	}
	return nil
}

func (x *DeltaResponse) GetRemovedLinks() []*LayoutLink {
	if x != nil {
		return x.RemovedLinks
	}
	return nil
}

func (x *DeltaResponse) GetCurrentHash() string {
	if x != nil {
		return x.CurrentHash
	}
	return ""
}

type NeighborRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId string `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Depth  int32  `protobuf:"varint,2,opt,name=depth,proto3" json:"depth,omitempty"`
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *NeighborRequest) Reset() {
	*x = NeighborRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeighborRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborRequest) ProtoMessage() {}

func (x *NeighborRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborRequest.ProtoReflect.Descriptor instead.
func (*NeighborRequest) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{8}
}

func (x *NeighborRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *NeighborRequest) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *NeighborRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NeighborNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type     string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Weight   float64 `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Distance int32   `protobuf:"varint,5,opt,name=distance,proto3" json:"distance,omitempty"`
}

func (x *NeighborNode) Reset() {
	*x = NeighborNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeighborNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborNode) ProtoMessage() {}

func (x *NeighborNode) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborNode.ProtoReflect.Descriptor instead.
func (*NeighborNode) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{9}
}

func (x *NeighborNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NeighborNode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NeighborNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NeighborNode) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *NeighborNode) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type NeighborResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NeighborNode `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *NeighborResponse) Reset() {
	*x = NeighborResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NeighborResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeighborResponse) ProtoMessage() {}

func (x *NeighborResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeighborResponse.ProtoReflect.Descriptor instead.
func (*NeighborResponse) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{10}
}

func (x *NeighborResponse) GetNodes() []*NeighborNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type PathRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromId string `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	ToId   string `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{11}
}

func (x *PathRequest) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *PathRequest) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *PathRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteIds  []string `protobuf:"bytes,1,rep,name=note_ids,json=noteIds,proto3" json:"note_ids,omitempty"`
	Distance int32    `protobuf:"varint,2,opt,name=distance,proto3" json:"distance,omitempty"`
	Weight   float64  `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
}

func (x *PathResponse) Reset() {
	*x = PathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathResponse) ProtoMessage() {}

func (x *PathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathResponse.ProtoReflect.Descriptor instead.
func (*PathResponse) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{12}
}

func (x *PathResponse) GetNoteIds() []string {
	if x != nil {
		return x.NoteIds
	}
	return nil
}

func (x *PathResponse) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *PathResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type RecommendationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId string `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit  int32  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *RecommendationsRequest) Reset() {
	*x = RecommendationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsRequest) ProtoMessage() {}

func (x *RecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsRequest.ProtoReflect.Descriptor instead.
func (*RecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{13}
}

func (x *RecommendationsRequest) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *RecommendationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RecommendationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type Recommendation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NoteId        string  `protobuf:"bytes,1,opt,name=note_id,json=noteId,proto3" json:"note_id,omitempty"`
	Title         string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Score         float64 `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	GraphScore    float64 `protobuf:"fixed64,4,opt,name=graph_score,json=graphScore,proto3" json:"graph_score,omitempty"`
	SemanticScore float64 `protobuf:"fixed64,5,opt,name=semantic_score,json=semanticScore,proto3" json:"semantic_score,omitempty"`
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{14}
}

func (x *Recommendation) GetNoteId() string {
	if x != nil {
		return x.NoteId
	}
	return ""
}

func (x *Recommendation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Recommendation) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Recommendation) GetGraphScore() float64 {
	if x != nil {
		return x.GraphScore
	}
	return 0
}

func (x *Recommendation) GetSemanticScore() float64 {
	if x != nil {
		return x.SemanticScore
	}
	return 0
}

type RecommendationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recommendations []*Recommendation `protobuf:"bytes,1,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
}

func (x *RecommendationsResponse) Reset() {
	*x = RecommendationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_graph_layout_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationsResponse) ProtoMessage() {}

func (x *RecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graph_layout_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationsResponse.ProtoReflect.Descriptor instead.
func (*RecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_graph_layout_proto_rawDescGZIP(), []int{15}
}

func (x *RecommendationsResponse) GetRecommendations() []*Recommendation {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

var File_graph_layout_proto protoreflect.FileDescriptor

var file_graph_layout_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x6c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x5b, 0x0a, 0x11, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x84, 0x01, 0x0a, 0x0a, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x01, 0x79, 0x12, 0x0c, 0x0a, 0x01, 0x7a, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x01, 0x7a, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x92, 0x01, 0x0a, 0x0a, 0x4c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x0e,
	0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x2e,
	0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x22, 0x42, 0x0a, 0x11, 0x46, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x88, 0x01, 0x0a, 0x0b, 0x4c, 0x61, 0x79, 0x6f, 0x75,
	0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x2e, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52,
	0x05, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x49,
	0x64, 0x22, 0x44, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x22, 0xcb, 0x02, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x74,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x61, 0x64, 0x64,
	0x65, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x61,
	0x79, 0x6f, 0x75, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x65, 0x64, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x3d, 0x0a, 0x0d, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x0c, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x39, 0x0a, 0x0b, 0x61, 0x64, 0x64, 0x65,
	0x64, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x79,
	0x6f, 0x75, 0x74, 0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x0a, 0x61, 0x64, 0x64, 0x65, 0x64, 0x4c, 0x69,
	0x6e, 0x6b, 0x73, 0x12, 0x3d, 0x0a, 0x0d, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x5f, 0x6c,
	0x69, 0x6e, 0x6b, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x4c, 0x69, 0x6e, 0x6b, 0x52, 0x0c, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x4c, 0x69, 0x6e,
	0x6b, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x48, 0x61, 0x73, 0x68, 0x22, 0x59, 0x0a, 0x0f, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x7c, 0x0a, 0x0c, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x44,
	0x0a, 0x10, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x30, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x22, 0x54, 0x0a, 0x0b, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x72, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x13, 0x0a, 0x05,
	0x74, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x49,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x5d, 0x0a, 0x0c, 0x50, 0x61,
	0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f,
	0x74, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f,
	0x74, 0x65, 0x49, 0x64, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x60, 0x0a, 0x16, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x9d, 0x01, 0x0a, 0x0e,
	0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17,
	0x0a, 0x07, 0x6e, 0x6f, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x6e, 0x6f, 0x74, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x5f, 0x73, 0x63, 0x6f,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x70, 0x68, 0x53,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63,
	0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x73, 0x65,
	0x6d, 0x61, 0x6e, 0x74, 0x69, 0x63, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x61, 0x0a, 0x17, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x72,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0xe6,
	0x03, 0x0a, 0x0c, 0x47, 0x72, 0x61, 0x70, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x12, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x4e, 0x6f, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x4d, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74,
	0x12, 0x1f, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x46, 0x75, 0x6c, 0x6c, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x4c, 0x61, 0x79, 0x6f, 0x75, 0x74, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x12, 0x43,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x12, 0x1a, 0x2e, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62,
	0x6f, 0x72, 0x73, 0x12, 0x1d, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x4e, 0x65, 0x69, 0x67, 0x68, 0x62, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x68, 0x12, 0x19, 0x2e,
	0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x74,
	0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x24, 0x2e, 0x67, 0x72, 0x61,
	0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x25, 0x2e, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x67, 0x72, 0x61, 0x70, 0x68, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_graph_layout_proto_rawDescOnce sync.Once
	file_graph_layout_proto_rawDescData = file_graph_layout_proto_rawDesc
)

func file_graph_layout_proto_rawDescGZIP() []byte {
	file_graph_layout_proto_rawDescOnce.Do(func() {
		file_graph_layout_proto_rawDescData = protoimpl.X.CompressGZIP(file_graph_layout_proto_rawDescData)
	})
	return file_graph_layout_proto_rawDescData
}

var file_graph_layout_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_graph_layout_proto_goTypes = []any{
	(*NoteLayoutRequest)(nil),       // 0: graphservice.NoteLayoutRequest
	(*LayoutNode)(nil),              // 1: graphservice.LayoutNode
	(*LayoutLink)(nil),              // 2: graphservice.LayoutLink
	(*LayoutResponse)(nil),          // 3: graphservice.LayoutResponse
	(*FullLayoutRequest)(nil),       // 4: graphservice.FullLayoutRequest
	(*LayoutChunk)(nil),             // 5: graphservice.LayoutChunk
	(*DeltaRequest)(nil),            // 6: graphservice.DeltaRequest
	(*DeltaResponse)(nil),           // 7: graphservice.DeltaResponse
	(*NeighborRequest)(nil),         // 8: graphservice.NeighborRequest
	(*NeighborNode)(nil),            // 9: graphservice.NeighborNode
	(*NeighborResponse)(nil),        // 10: graphservice.NeighborResponse
	(*PathRequest)(nil),             // 11: graphservice.PathRequest
	(*PathResponse)(nil),            // 12: graphservice.PathResponse
	(*RecommendationsRequest)(nil),  // 13: graphservice.RecommendationsRequest
	(*Recommendation)(nil),          // 14: graphservice.Recommendation
	(*RecommendationsResponse)(nil), // 15: graphservice.RecommendationsResponse
}
var file_graph_layout_proto_depIdxs = []int32{
	1,  // 0: graphservice.LayoutResponse.nodes:type_name -> graphservice.LayoutNode
	2,  // 1: graphservice.LayoutResponse.links:type_name -> graphservice.LayoutLink
	1,  // 2: graphservice.LayoutChunk.nodes:type_name -> graphservice.LayoutNode
	2,  // 3: graphservice.LayoutChunk.links:type_name -> graphservice.LayoutLink
	1,  // 4: graphservice.DeltaResponse.added_nodes:type_name -> graphservice.LayoutNode
	1,  // 5: graphservice.DeltaResponse.updated_nodes:type_name -> graphservice.LayoutNode
	2,  // 6: graphservice.DeltaResponse.added_links:type_name -> graphservice.LayoutLink
	2,  // 7: graphservice.DeltaResponse.removed_links:type_name -> graphservice.LayoutLink
	9,  // 8: graphservice.NeighborResponse.nodes:type_name -> graphservice.NeighborNode
	14, // 9: graphservice.RecommendationsResponse.recommendations:type_name -> graphservice.Recommendation
	0,  // 10: graphservice.GraphService.GetNoteLayout:input_type -> graphservice.NoteLayoutRequest
	4,  // 11: graphservice.GraphService.GetFullLayout:input_type -> graphservice.FullLayoutRequest
	6,  // 12: graphservice.GraphService.GetDelta:input_type -> graphservice.DeltaRequest
	8,  // 13: graphservice.GraphService.GetNeighbors:input_type -> graphservice.NeighborRequest
	11, // 14: graphservice.GraphService.GetPath:input_type -> graphservice.PathRequest
	13, // 15: graphservice.GraphService.GetRecommendations:input_type -> graphservice.RecommendationsRequest
	3,  // 16: graphservice.GraphService.GetNoteLayout:output_type -> graphservice.LayoutResponse
	5,  // 17: graphservice.GraphService.GetFullLayout:output_type -> graphservice.LayoutChunk
	7,  // 18: graphservice.GraphService.GetDelta:output_type -> graphservice.DeltaResponse
	10, // 19: graphservice.GraphService.GetNeighbors:output_type -> graphservice.NeighborResponse
	12, // 20: graphservice.GraphService.GetPath:output_type -> graphservice.PathResponse
	15, // 21: graphservice.GraphService.GetRecommendations:output_type -> graphservice.RecommendationsResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_graph_layout_proto_init() }
func file_graph_layout_proto_init() {
	if File_graph_layout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_graph_layout_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NoteLayoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*LayoutNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LayoutLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LayoutResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*FullLayoutRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LayoutChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*DeltaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*DeltaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*NeighborRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*NeighborNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*NeighborResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*PathRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*PathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RecommendationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*Recommendation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_graph_layout_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RecommendationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_graph_layout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graph_layout_proto_goTypes,
		DependencyIndexes: file_graph_layout_proto_depIdxs,
		MessageInfos:      file_graph_layout_proto_msgTypes,
	}.Build()
	File_graph_layout_proto = out.File
	file_graph_layout_proto_rawDesc = nil
	file_graph_layout_proto_goTypes = nil
	file_graph_layout_proto_depIdxs = nil
}
